Models/Book.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Books.Models
{
    public class Book
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Title")]
        public string Name { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Range(1, 10)]
        [DataType(DataType.Currency)]
        public Decimal Price { get; set; }

        [Display(Name = "Book Cover")]
        public byte[] Image { get; set; }

        [ForeignKey("Person")]
        [Display(Name = "Author")]
        public int? PersonID { get; set; }

        [ForeignKey("Genre")]
        [Display(Name = "Genre")]
        public int? GenreID { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual Person Person { get; set; }
    }
}

Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;
using Books.Common;

namespace Books.Controllers
{
    public class BooksController : Controller
    {
        private BooksDbContext db = new BooksDbContext();

        // GET: Books
        public ActionResult Index()
        {
            var books = db.Books.Include(b => b.Genre).Include(b => b.Person);
            return View(books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            var authors = db.Persons.Where(p => p.PersonTypeID == (int)PersonTypeValue.Author);
            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name");
            ViewBag.PersonID = new SelectList(authors, "ID", "Name");
            ViewBag.AuthorID = new SelectList(authors, "ID", "FirstName");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description,Price,Image,PersonID,GenreID")] Book book, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                    book.Image = Utility.GetImage(upload);

                db.Books.Add(book);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name", book.GenreID);
            ViewBag.PersonID = new SelectList(db.Persons, "ID", "Name", book.PersonID);
            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            var authors = db.Persons.Where(p => p.PersonTypeID == (int)PersonTypeValue.Author);
            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name", book.GenreID);
            ViewBag.PersonID = new SelectList(authors, "ID", "Name", book.PersonID);
            ViewBag.AuthorID = new SelectList(authors, "ID", "FirstName", book.PersonID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Price,Image,PersonID,GenreID")] Book book, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                db.Entry(book).State = EntityState.Modified;

                if (upload != null)
                    book.Image = Utility.GetImage(upload);
                else
                    db.Entry(book).Property(m => m.Image).IsModified = false;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name", book.GenreID);
            ViewBag.PersonID = new SelectList(db.Persons, "ID", "Name", book.PersonID);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Books.Find(id);
            db.Books.Remove(book);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/CommonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;

namespace Books.Controllers
{
    public class CommonsController : Controller
    {
        private BooksDbContext db = new BooksDbContext();

        // GET: Commons
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCountry(int stateId)
        {
            IQueryable<Country> countries = db.States.Where(s => s.ID == stateId).Select(s => s.Country);

            return Json(countries.FirstOrDefault().Name, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetState(int cityId)
        {
            IQueryable<State> states = db.Cities.Where(c => c.ID == cityId).Select(c => c.State);

            return Json(states.FirstOrDefault(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAuthors(string name)
        {
            var persons = db.Persons.Where(p => p.Name == name).ToList();

            return Json(persons, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Books/Create.cshtml
@model Books.Models.Book

@using (Html.BeginForm("Create", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <br />

    <div class="form-horizontal table-bordered img-rounded">
        <h4><span class="header-books">Add New Book</span></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetAuthors()" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorID", null, string.Empty, htmlAttributes: new { @class = "form-control", @id = "Authors" })
            </div>
        </div>
       
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 4 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                <div class="input-group">
                    <span class="input-group-btn">
                        <label class="btn btn-default btn-file">
                            Browse<input type="file" id="upload" name="upload" accept="image/*" />
                        </label>
                    </span>
                    <input type="text" id="filename" class="form-control" placeholder="Search for...">
                </div>
                <img id="image" />
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="footer-books">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>

        function GetAuthors() {
            GetAuthorsService('@Url.Action("GetAuthors", "Commons")');
        }

        $('#upload').on("change", function () {
            uploadFile(this);
        });

    </script>

}

Views/Books/Delete.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Books/Details.cshtml
@model Books.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Books/Edit.cshtml
@model Books.Models.Book

@using (Html.BeginForm("Edit", "Books", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <br />

    <div class="form-horizontal table-bordered img-rounded">
        <h4><span class="header-books">Edit Book</span></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetAuthors()" })
                @Html.ValidationMessageFor(model => model.PersonID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorID", null, string.Empty, htmlAttributes: new { @class = "form-control", @id = "Authors" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = 4 })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-lg-6">
                <div class="input-group">
                    <span class="input-group-btn">
                        <label class="btn btn-default btn-file">
                            Browse<input type="file" id="upload" name="upload" accept="image/*" style="display: none;" onchange="readURL(this);" />
                        </label>
                    </span>
                    <input type="text" id="filename" class="form-control" placeholder="Search for...">
                </div>
                @if (Model.Image != null)
                {
                    <img id="image" src="data:image; base64, @System.Convert.ToBase64String(Model.Image)" />
                } 
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script>

        function GetAuthors() {
            GetAuthorsService('@Url.Action("GetAuthors", "Commons")');
        }

        $('#upload').on("change", function () {
            uploadFile(this);
        });

</script>

}

Views/Books/Index.cshtml
@model IEnumerable<Books.Models.Book>

<div>
    <div class='btn-toolbar pull-right'>
        <div class='btn-group'>
            <p>@Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary pull-right" })</p>
        </div>
    </div>
    <h2>Books</h2>
</div>

<table class="table">
    <tr>
        <th>
            Cover
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PersonID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.Image != null)
            {
                <img src="data:image; base64, @System.Convert.ToBase64String(item.Image)" />
            }  
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td class="col-md-2">
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td class="col-md-2">
            @Html.DisplayFor(modelItem => item.Person.FirstName) @Html.DisplayFor(modelItem => item.Person.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td class="col-md-2">
            <div class="btn-group pull-right" role="group">
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </div>
        </td>
    </tr>
}

</table>