Models/Person.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Books.Models
{
    public class Person
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Last Name")]
        public string Name { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateOfBirth { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Street Name")]
        public string StreetName { get; set; }

        [Required]
        [Display(Name = "Address Number")]
        public int Number { get; set; }

        [StringLength(5)]
        [Display(Name = "Address Extension")]
        public string Extension { get; set; }

        [Required]
        [StringLength(25)]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [StringLength(25)]
        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [ForeignKey("Gender")]
        [Display(Name = "Gender")]
        public int? GenderID { get; set; }

        [ForeignKey("City")]
        [Display(Name = "City")]
        public int? CityID { get; set; }

        [ForeignKey("CityAddress")]
        [Display(Name = "City")]
        public int? CityAddressID { get; set; }

        [ForeignKey("PersonType")]
        [Display(Name = "Type")]
        public int? PersonTypeID { get; set; }

        public virtual PersonType PersonType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual City CityAddress { get; set; }
        public virtual City City { get; set; }
    }
}

Models/PersonType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Books.Models
{
    public enum PersonTypeValue
    {
        Patron = 1,
        Author = 2
    }

    public class PersonType
    {
        [Key]
        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        [Display(Name = "Person Type")]
        public string Name { get; set; }
    }
}

Controllers/CommonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;

namespace Books.Controllers
{
    public class CommonsController : Controller
    {
        private BooksDbContext db = new BooksDbContext();

        // GET: Commons
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetCountry(int stateId)
        {
            IQueryable<Country> countries = db.States.Where(s => s.ID == stateId).Select(s => s.Country);

            return Json(countries.FirstOrDefault().Name, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetState(int cityId)
        {
            IQueryable<State> states = db.Cities.Where(c => c.ID == cityId).Select(c => c.State);

            return Json(states.FirstOrDefault(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAuthors(string name)
        {
            var persons = db.Persons.Where(p => p.Name == name).ToList();

            return Json(persons, JsonRequestBehavior.AllowGet);
        }
    }
}

Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Books.Models;

namespace Books.Controllers
{
    public class PersonsController : Controller
    {
        private BooksDbContext db = new BooksDbContext();

        // GET: Persons/Type/2
        public ActionResult Index(int typeId)
        {
            var persons = db.Persons
                                .Include(p => p.City)
                                .Include(p => p.CityAddress)
                                .Include(p => p.Gender)
                                .Where(p => p.PersonTypeID == typeId);
            return View(persons.ToList());
        }

        // GET: Persons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // GET: Persons/Create        
        public ActionResult Create(int typeId)
        {
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name");
            ViewBag.CityAddressID = new SelectList(db.Cities, "ID", "Name");
            ViewBag.GenderID = new SelectList(db.Genders, "ID", "Name");
            ViewBag.PersonTypeID = new SelectList(db.PersonTypes, "ID", "Name", typeId);
            return View();
        }

        // POST: Persons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,FirstName,DateOfBirth,StreetName,Number,Extension,Phone,Email,GenderID,CityID,CityAddressID,PersonTypeID")] Person person, int typeId)
        {
            if (ModelState.IsValid)
            {
                person.PersonTypeID = typeId;
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index", new { typeId = person.PersonTypeID });
            }

            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", person.CityID);
            ViewBag.CityAddressID = new SelectList(db.Cities, "ID", "Name", person.CityAddressID);
            ViewBag.GenderID = new SelectList(db.Genders, "ID", "Name", person.GenderID);
            return View(person);
        }

        // GET: Persons/Edit/5
        public ActionResult Edit(int? id, int typeId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {   
                return HttpNotFound();
            }
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", person.CityID);
            ViewBag.CityAddressID = new SelectList(db.Cities, "ID", "Name", person.CityAddressID);
            ViewBag.GenderID = new SelectList(db.Genders, "ID", "Name", person.GenderID);
            ViewBag.PersonTypeID = new SelectList(db.PersonTypes, "ID", "Name", person.PersonTypeID);
            ViewBag.TypeID = typeId;

            return View(person);
        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,FirstName,DateOfBirth,StreetName,Number,Extension,Phone,Email,GenderID,CityID,CityAddressID,PersonTypeID")] Person person, int typeId)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                person.PersonTypeID = typeId;
                db.SaveChanges();
                return RedirectToAction("Index", new { typeId = person.PersonTypeID });
            }
            ViewBag.CityID = new SelectList(db.Cities, "ID", "Name", person.CityID);
            ViewBag.CityAddressID = new SelectList(db.Cities, "ID", "Name", person.CityAddressID);
            ViewBag.GenderID = new SelectList(db.Genders, "ID", "Name", person.GenderID);
            ViewBag.PersonTypeID = new SelectList(db.PersonTypes, "ID", "Name", typeId);
            return View(person);
        }

        // GET: Persons/Delete/5        
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                return HttpNotFound();
            }
            return View(person);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int typeId, int id)
        {
            Person person = db.Persons.Find(id);            
            db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index", new { typeId = typeId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Persons/Create.cshtml
@model Books.Models.Person

@using (Html.BeginForm("Create", "Persons", FormMethod.Post, new { typeId = (int)ViewBag.PersonTypeID.SelectedValue }))
{
    @Html.AntiForgeryToken()

    <br />

    <div class="form-horizontal table-bordered img-rounded">
        <h4><span class="header-books">Add New Person</span></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonTypeID", null, string.Empty, htmlAttributes: new { @class = "form-control", @disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Place of Birth</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetState('#CityID', '#State', '#Country')" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City.State.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.State.Name, new { htmlAttributes = new { @class = "form-control", @id = "State", @disabled= "disabled" } })                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City.State.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.State.Country.Name, new { htmlAttributes = new { @class = "form-control", @id = "Country", @disabled = "disabled" } })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Address</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddressID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityAddressID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetState('#CityAddressID', '#StateAddress', '#CountryAddress')" })
                @Html.ValidationMessageFor(model => model.CityAddressID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddress.State.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityAddress.State.Name, new { htmlAttributes = new { @class = "form-control", @id = "StateAddress", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddress.State.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityAddress.State.Country.Name, new { htmlAttributes = new { @class = "form-control", @id = "CountryAddress", @disabled = "disabled" } })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Contact Information</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="footer-books">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
            function GetState(cityField, stateField, countryField) {
                GetStateService('@Url.Action("GetState", "Commons")', cityField, stateField, countryField);
                }
    </script>

}

Views/Persons/Delete.cshtml
@model Books.Models.Person

<br />

<div class="form-horizontal table-bordered img-rounded">
    <h4><span class="header-books">Are you sure you want to delete this?</span></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Address
        </dt>
            
        <dd>
            @Html.DisplayFor(model => model.StreetName) @Html.DisplayFor(model => model.Number) @Html.DisplayFor(model => model.Extension)
            <br />
            @Html.DisplayFor(model => model.CityAddress.Name), @Html.DisplayFor(model => model.CityAddress.State.Name)
            <br />
            @Html.DisplayFor(model => model.CityAddress.State.Country.Name)
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Telephone Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)            
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        
    </dl>

    @using (Html.BeginForm("Delete", "Persons", FormMethod.Post, new { typeId = Model.PersonTypeID, id = Model.ID }))
    {
        @Html.AntiForgeryToken()

        <p>
            <span class="header-books">
                <input type="submit" value="Delete" class="btn btn-default" />
            </span>
        </p>

    }
</div>

<div class="footer-books">
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Persons/Details.cshtml
@model Books.Models.Person

<br />

<div class="form-horizontal table-bordered img-rounded">
    <h4><span class="header-books">Person Details</span></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StreetName) @Html.DisplayFor(model => model.Number) @Html.DisplayFor(model => model.Extension)
            <br />
            @Html.DisplayFor(model => model.CityAddress.Name), @Html.DisplayFor(model => model.CityAddress.State.Name)
            <br />
            @Html.DisplayFor(model => model.CityAddress.State.Country.Name)
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Telephone Number
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            &nbsp;
        </dt>
        <dd>
            &nbsp;
        </dd>

        <dt>
            Email
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<div class="footer-books">
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Persons/Edit.cshtml
@model Books.Models.Person

@using (Html.BeginForm("Edit", "Persons", FormMethod.Post, new { typeId = (int)ViewBag.TypeID }))
{
    @Html.AntiForgeryToken()

    <br />

    <div class="form-horizontal table-bordered img-rounded">
        <h4><span class="header-books">Edit Person</span></h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenderID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonTypeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonTypeID", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Place of Birth</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetState('#CityID', '#State', '#Country')" })
                @Html.ValidationMessageFor(model => model.CityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City.State.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.State.Name, new { htmlAttributes = new { @class = "form-control", @id = "State", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City.State.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City.State.Country.Name, new { htmlAttributes = new { @class = "form-control", @id = "Country", @disabled = "disabled" } })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Address</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.StreetName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StreetName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StreetName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Extension, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Extension, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Extension, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddressID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CityAddressID", null, string.Empty, htmlAttributes: new { @class = "form-control", @onchange = "GetState('#CityAddressID', '#StateAddress', '#CountryAddress')" })
                @Html.ValidationMessageFor(model => model.CityAddressID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddress.State.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityAddress.State.Name, new { htmlAttributes = new { @class = "form-control", @id = "StateAddress", @disabled = "disabled" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityAddress.State.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityAddress.State.Country.Name, new { htmlAttributes = new { @class = "form-control", @id = "CountryAddress", @disabled = "disabled" } })
            </div>
        </div>

        <hr />
        <h4><span class="header-books">Contact Information</span></h4>
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="footer-books">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
                function GetState(cityField, stateField, countryField) {
                    GetStateService('@Url.Action("GetState", "Commons")', cityField, stateField, countryField);
                    }
    </script>

}

Views/Persons/Index.cshtml
@model IEnumerable<Books.Models.Person>

<div>
    <div class='btn-toolbar pull-right'>
        <div class='btn-group'>
            <p>@Html.ActionLink("Create New", "Create", new { typeId = Model.FirstOrDefault().PersonTypeID }, new { @class = "btn btn-primary pull-right" })</p>
        </div>
    </div>
    <h2>Persons</h2>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            Place of Birth
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City.Name), @Html.DisplayFor(modelItem => item.City.State.Name), @Html.DisplayFor(modelItem => item.City.State.Country.Name)
        </td>
        <td>
            <span class="pull-right">
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </span>
        </td>
    </tr>
}

</table>